README.md, charts/prometheus-msteams/Chart.yaml, charts/prometheus-msteams/README.md
=> deprecate prometheus-msteams

charts/access-manager/.helmignore, charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/crds/rbacdefinitions.yaml, charts/access-manager/templates/NOTES.txt, charts/access-manager/templates/_helpers.tpl, charts/access-manager/templates/clusterrolebinding.yaml, charts/access-manager/templates/deployment.yaml, charts/access-manager/templates/serviceaccount.yaml, charts/access-manager/values.yaml
=> initial access-manager chart

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/crds/rbacdefinitions.yaml, charts/access-manager/templates/deployment.yaml, charts/access-manager/values.yaml
https://github.com/ckotzbauer/access-manager/releases/tag/0.3.0
=> updated access-manager to 0.3.0

charts/cadvisor/Chart.yaml, charts/cadvisor/README.md, charts/cadvisor/templates/psp.yaml, charts/cadvisor/values.yaml
Update cAdvisor application version
Set into the podSecurityPolicy the possibility to run as privileged.
=> chore: Update appVersion and psp as privileged

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/crds/rbacdefinitions.yaml, charts/access-manager/values.yaml
=> update access-manager to 0.4.0

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/templates/crd.yaml, charts/access-manager/values.yaml
=> Update access-manager to 0.4.1

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/README.md, charts/prometheus-blackbox-exporter/values.yaml
=> Update blackbox-exporter to 0.18.0

charts/cadvisor/Chart.yaml, charts/cadvisor/README.md, charts/cadvisor/values.yaml
=> update cadvisor to 0.38.4

charts/nfs-client-provisioner/Chart.yaml, charts/nfs-client-provisioner/README.md, charts/nfs-client-provisioner/templates/persistentvolume.yaml, charts/nfs-client-provisioner/templates/persistentvolumeclaim.yaml, charts/nfs-client-provisioner/values.yaml
this add accessModes so it can be the same as the main `stable/nfs-client-provisioner` repo
=> add accessModes

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/templates/crd.yaml, charts/access-manager/values.yaml
=> update access-manager to 0.5.0

charts/cadvisor/Chart.yaml, charts/cadvisor/README.md, charts/cadvisor/values.yaml
=> update cadvisor to 0.38.6

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/templates/crd.yaml, charts/access-manager/values.yaml
=> update access-manager to 0.5.1

charts/access-manager/Chart.yaml, charts/access-manager/templates/deployment.yaml
=> fix: annotation-placeholder in access-manager chart

charts/access-manager/Chart.yaml, charts/access-manager/values.yaml
=> feat: access-manager: runAsNonRoot: true

charts/cadvisor/Chart.yaml, charts/cadvisor/README.md, charts/cadvisor/values.yaml
=> feat: update cadvisor

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/README.md, charts/prometheus-blackbox-exporter/values.yaml
=> feat: update blackbox-exporter

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/values.yaml
=> feat: update to access-manager@0.6.0

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/values.yaml
=> update to access-manager 0.7.0

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/templates/crd.yaml, charts/access-manager/values.yaml
=> update access-manager to 0.8.0

charts/postgres-operator/Chart.yaml, charts/postgres-operator/README.md, charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/crds/postgresqls.yaml, charts/postgres-operator/values.yaml
=> update postgres-operator to 1.7.1

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/values.yaml
=> update access-manager to 0.8.1

README.md, charts/sbom-operator/.helmignore, charts/sbom-operator/Chart.yaml, charts/sbom-operator/README.md, charts/sbom-operator/templates/NOTES.txt, charts/sbom-operator/templates/_helpers.tpl, charts/sbom-operator/templates/clusterrole.yaml, charts/sbom-operator/templates/clusterrolebinding.yaml, charts/sbom-operator/templates/deployment.yaml, charts/sbom-operator/templates/serviceaccount.yaml, charts/sbom-operator/values.yaml
=> feat: added sbom-operator

charts/sbom-operator/Chart.yaml, charts/sbom-operator/README.md, charts/sbom-operator/templates/deployment.yaml, charts/sbom-operator/values.yaml
=> feat: update to sbom-operator@0.2.0

charts/sbom-operator/Chart.yaml, charts/sbom-operator/README.md, charts/sbom-operator/templates/clusterrole.yaml
=> Update sbom-operator to 0.3.0

README.md, charts/vulnerability-operator/.helmignore, charts/vulnerability-operator/Chart.yaml, charts/vulnerability-operator/README.md, charts/vulnerability-operator/templates/NOTES.txt, charts/vulnerability-operator/templates/_helpers.tpl, charts/vulnerability-operator/templates/clusterrole.yaml, charts/vulnerability-operator/templates/clusterrolebinding.yaml, charts/vulnerability-operator/templates/deployment.yaml, charts/vulnerability-operator/templates/ingress.yaml, charts/vulnerability-operator/templates/service.yaml, charts/vulnerability-operator/templates/serviceaccount.yaml, charts/vulnerability-operator/templates/servicemonitor.yaml, charts/vulnerability-operator/values.yaml
=> Add vulnerability-operator

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/values.yaml
=> update access-manager to 0.9.0

.github/workflows/lint-test.yaml, charts/postgres-operator/Chart.yaml, charts/postgres-operator/README.md, charts/postgres-operator/crds/operatorconfigurations.yaml, charts/postgres-operator/crds/postgresqls.yaml, charts/postgres-operator/crds/postgresteams.yaml, charts/postgres-operator/templates/clusterrole-postgres-pod.yaml, charts/postgres-operator/templates/clusterrole.yaml, charts/postgres-operator/templates/crds.yaml, charts/postgres-operator/templates/user-facing-clusterroles.yaml, charts/postgres-operator/values.yaml
=> update postgres-operator to 1.8.0

charts/cadvisor/Chart.yaml, charts/cadvisor/README.md, charts/cadvisor/templates/daemonset.yaml, charts/cadvisor/values.yaml
add priorityClassName to cadvisor  helm chart daemonset.yaml
=> (feature):add priorityClassName to daemonset

charts/sbom-operator/Chart.yaml, charts/sbom-operator/ci/all-args-values.yaml, charts/sbom-operator/ci/all-env-values.yaml, charts/sbom-operator/templates/deployment.yaml
=> SBOM-Operator Environment Variable Config Fix

charts/sbom-operator/Chart.yaml, charts/sbom-operator/README.md, charts/vulnerability-operator/Chart.yaml, charts/vulnerability-operator/README.md, charts/vulnerability-operator/templates/deployment.yaml, charts/vulnerability-operator/values.yaml
=> feat: updated sbom- and vulnerability-operator

charts/cadvisor/Chart.yaml, charts/cadvisor/README.md, charts/cadvisor/templates/servicemonitor.yaml, charts/cadvisor/values.yaml
Hi,
I have noticed that those 2 parameters are not exposed, could use to be able to set them. Is it fine to do so?
=> Add scrape interval and timeout for cadvisor service monitor

charts/cadvisor/Chart.yaml, charts/cadvisor/templates/clusterrole.yaml, charts/cadvisor/templates/clusterrolebinding.yaml, charts/cadvisor/templates/daemonset.yaml, charts/cadvisor/templates/psp.yaml, charts/cadvisor/templates/service.yaml
=> Set cAdvisor namespace for all templates with release namespace

charts/cadvisor/Chart.yaml, charts/cadvisor/README.md, charts/cadvisor/templates/daemonset.yaml, charts/cadvisor/values.yaml
=> add support for podlabels in cadvisor

charts/access-manager/Chart.yaml, charts/access-manager/README.md, charts/access-manager/templates/deployment.yaml, charts/access-manager/values.yaml, charts/sbom-operator/Chart.yaml, charts/sbom-operator/README.md, charts/sbom-operator/templates/deployment.yaml, charts/sbom-operator/values.yaml, charts/vulnerability-operator/Chart.yaml, charts/vulnerability-operator/README.md, charts/vulnerability-operator/templates/deployment.yaml, charts/vulnerability-operator/values.yaml
added support to set priorityClassName in access manger, sbom-operator and vulnerability-operator
=> Add priority class name

charts/cadvisor/templates/_helpers.tpl, charts/cadvisor/templates/clusterrole.yaml, charts/cadvisor/templates/clusterrolebinding.yaml, charts/cadvisor/templates/daemonset.yaml, charts/cadvisor/templates/psp.yaml, charts/cadvisor/templates/service.yaml, charts/cadvisor/templates/serviceaccount.yaml, charts/cadvisor/templates/servicemonitor.yaml, charts/cadvisor/values.yaml
The aim of this PR is to adapt labels with Kubernetes standard ones, as well as adding a commonLabels to add to all resources as extra labels.
=> Adapt labels to kubernetes standard
